// gen-docs writes docs/rules.md from the rule catalogue compiled into the binary.
//
// The catalogue is the documentation, so it must not be maintained twice: CI
// regenerates this file and fails if the result differs from what is committed.
// Run it after adding or editing a rule:
//
//	go run ./cmd/gen-docs
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/Allan-Nava/keycloak-doctor/internal/rules"
)

const outPath = "docs/rules.md"

func main() {
	all := rules.All()
	byCategory := map[string][]rules.Rule{}
	for _, r := range all {
		byCategory[r.Category()] = append(byCategory[r.Category()], r)
	}
	categories := make([]string, 0, len(byCategory))
	for c := range byCategory {
		categories = append(categories, c)
	}
	sort.Strings(categories)

	b := &strings.Builder{}
	b.WriteString("<!-- Generated by `go run ./cmd/gen-docs`. Do not edit by hand. -->\n\n")
	b.WriteString("# Rules\n\n")
	fmt.Fprintf(b, "keycloak-doctor ships %d rules in %d categories. Every rule is evaluated against a\n", len(all), len(categories))
	b.WriteString("realm read either from an export file or from the Admin REST API; the id is stable\n")
	b.WriteString("and is what `--only`, `--skip` and any suppression in your pipeline should pin.\n\n")
	b.WriteString("A run can also report `suppression/expired` and `suppression/unmatched`. Those are not\n")
	b.WriteString("realm rules — they are about your own suppression file — so they are documented in\n")
	b.WriteString("[ci.md](ci.md) rather than listed here, and `--only`/`--skip` do not select them.\n\n")
	b.WriteString("| Rule | Checks that |\n|---|---|\n")
	for _, r := range all {
		fmt.Fprintf(b, "| [`%s`](#%s) | %s |\n", r.ID, anchor(r.ID), r.Title)
	}
	b.WriteString("\n")

	for _, c := range categories {
		fmt.Fprintf(b, "## %s\n\n", c)
		for _, r := range byCategory[c] {
			fmt.Fprintf(b, "### `%s`\n\n**%s**\n\n%s\n\n", r.ID, r.Title, r.Rationale)
		}
	}

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil { //nolint:gosec // documentation, world-readable on purpose
		fmt.Fprintln(os.Stderr, "gen-docs:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d rules)\n", outPath, len(all))
}

// anchor renders the GitHub heading anchor of a rule id: the backticked heading
// "### `client/pkce`" anchors as #clientpkce.
func anchor(id string) string {
	return strings.ReplaceAll(strings.ToLower(id), "/", "")
}
